name: Build OpenSSL for Android

on:
  repository_dispatch:  # 监听来自其他仓库的手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the OpenSSL repository
      - name: Checkout OpenSSL repository
        uses: actions/checkout@v2
        with:
          repository: openssl/openssl  # 克隆 OpenSSL 仓库
          ref: openssl-3.5.2  # 指定 tag

      # Step 2: Set up Android NDK manually
      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          export ANDROID_NDK_ROOT=$PWD/android-ndk-r21e
          export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

      # Step 3: Build OpenSSL for different Android architectures
      - name: Build OpenSSL for Android
        run: |
          cd openssl
          ./Configure android-arm64 -D__ANDROID_API__=21 --prefix=$GITHUB_WORKSPACE/openssl-arm64
          make
          make install

          ./Configure android-arm -D__ANDROID_API__=21 --prefix=$GITHUB_WORKSPACE/openssl-arm
          make
          make install

          ./Configure android-x86_64 -D__ANDROID_API__=21 --prefix=$GITHUB_WORKSPACE/openssl-x86_64
          make
          make install

          ./Configure android-x86 -D__ANDROID_API__=21 --prefix=$GITHUB_WORKSPACE/openssl-x86
          make
          make install

      # Step 4: Upload the built OpenSSL libraries as artifacts
      - name: Upload OpenSSL artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openssl-libraries
          path: |
            $GITHUB_WORKSPACE/openssl-arm64
            $GITHUB_WORKSPACE/openssl-arm
            $GITHUB_WORKSPACE/openssl-x86_64
            $GITHUB_WORKSPACE/openssl-x86
