name: Trigger OpenSSL Build

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger OpenSSL Build in Another Repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "build-openssl"}' \
            https://api.github.com/repos/YOUR_USERNAME/YOUR_TARGET_REPO/dispatches
